/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-xZWcfans4OKXQH7-bzvYxS4WaFNxwttdJz-YC57GC4DtKMto9stS5Py1xjAxYoalGyReYeSg3DIBPzzg6DDvO6xnOrlZk8AwIc1crj5gdgFeeiwcQDKuDuxr",
  "tt": "tt-1-yH3Tz-doTJSmOolqmBQ-aKwEfbGva9-MdOx-iHa1EUI=",
  "version": "2020-11-20"
}

export default ebconfig;